### ISSUE TITLE
Add sample HTTP/proxy

### ISSUE THREAD

**Issue by Niklas-Schaefers** [Niklas-Schaefers/gitEncy#5]
#### Add sample HTTP 

Add sample HTTP requests with custom PORT and Proxy to /api

#### To Reproduce

[Sample HTTP](https://github.com/lmachens/photoplay/pull/49/commits/650917bc2d1d772c4226adaa6be41c02c090e95b)

[Sample Proxy](https://github.com/lmachens/photoplay/pull/49/commits/72b70aa2c7fff748c1e2bf021a00293a950c8945)

#### Tasks

- [x] Add proxy to API
- [x] Build sample HTTP
- [x] Use sample HTTP
- [x] Check data
