### ISSUE TITLE
Build API.ts

### ISSUE THREAD

**Issue by Niklas-Schaefers** [Niklas-Schaefers/gitEncy#6]
#### Create API functions

Create all necessary functions to get the requested data from API.

#### To Reproduce

[Sample](https://github.com/lmachens/photoplay/pull/49/commits/cb547e8bace337d68a1385fdc2c438ae314e2974)

#### Tasks

- [x] Create BASE_URL
- [x] Create fetch function
- [x] Create specific functions for API search
